apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend:v1
        name: frontend
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: "development"
        - name: VITE_TARGET
          value: "http://backend:3000/"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: frontend
