apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomoo-deployment
  labels:
    app: moomoo
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: moomoo
  template:
    metadata:
      labels:
        app: moomoo
    spec:
      containers:
      - name: moomoo-container
        image: moomoo:v1 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: moomoo-service
spec:
  selector:
    app: moomoo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
