apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
  labels:
    app: vue
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - name: vue-container
        image: vue:v1 
        ports:
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  selector:
    app: vue
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
