version: "3.9"

services:
  # FE service
  frontend:
    image: frontend:v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_TARGET=http://backend:3000/
    networks:
      - app-network

  # BE service
  backend:
    image: backend:v1
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=1
      - DB_NAME=pizza
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SWAGGER_HOST=backend
      - SWAGGER_PORT=3000
    volumes:
      - ./backend-api/public:/app/public
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: pizza
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend-api/src/database/pizza.sql:/docker-entrypoint-initdb.d/pizza.sql:ro
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-network

  # NGINX
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/server.key:/etc/ssl/private/server.key:ro
      - ./ssl/server.crt:/etc/ssl/certs/server.crt:ro
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
